name: Build Page

on:
  push:
    branches:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Yarn CLI
        uses: CultureHQ/actions-yarn@v1.0.1
      - name: Build
        run: |
          yarn install
          yarn build
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.PAGES_TOKEN }}
          BASE_BRANCH: gh-pages # The branch the action should deploy from.
          BRANCH: master # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.
